/**
* @file st_eth_mdio.h
* @brief STM32H7 Ethernet MDIO driver interface
* @author Bex Saw
*/

#pragma once

#include <cstdint>
#include "delay.h"
#include "eth_mdio.h"
#include "reg_helpers.h"
#include "stm32h723xx.h"

namespace EoT::StmH7
{

/**
* @brief Enumeration for MDIO clock range settings
* MCD clock selection -> basically a divider of the CSR clock (HCLK)
*  BitPos 1-5 are for the IEEE 802.3 standard clock range
*  BitPos 6-7 is RESERVED
*  BitPos 8-15 are for adaptable clock range above the IEEE 802.3 standard
*/
enum class MdioClockRange : uint8_t
{
    Div42 = 0,
    Div62 = 1,
    Div16 = 2,
    Div26 = 3,
    Div102 = 4,
    Div124 = 5,
    Div4 = 8,
    Div6 = 9,
    Div8 = 10,
    Div10 = 11,
    Div12 = 12,
    Div14 = 13,
    Div16Fast = 14,
    Div18 = 15,
};

/**
* @brief Enumeration for MDIO clause settings
* It means the type of MDIO protocol to use for communication with the PHY device.
* Clause 22 is the original MDIO protocol defined in IEEE 802.3
* Clause 45 is an extended MDIO protocol that allows access to a larger number of registers.
*/
enum class MdioClause : uint8_t
{
    Clause22 = 0,
    Clause45,
};

/**
* @brief struct for MDIO settings
*/
struct StEthMdioSettings
{
    MdioClockRange clock_range;
    MdioClause clause;
};

/** @note 
 *    RMII REF_CLK   = 50 MHz  <-- from PHY
 *    CSR/HCLK       = 100 MHz <-- from MCU clock tree
 *    MDC            ≈ 1.6 MHz <-- generated by MAC from HCLK
 */

/**
* The MAC initiates the management write or read operation with respect to the MDC clock.
* The MDC clock is derived from the CSR clock (eth_hclk). The maximum operating
* frequency of the ETH_MDC pin is 2.5 MHz, as specified in IEEE 802.3 specifications. 
*/

struct StEthMdioConfig
{
    ETH_TypeDef* base_addr;
    // CSR clock frequency (HCLK) in Hz.
    uint32_t csr_clock_hz{0U};
    // Timeout for MDIO read/write transactions in milliseconds.
    uint32_t timeout_ms{1000U};
    StEthMdioSettings settings;
};

class StEthMdio : public EoT::EthMdio<StEthMdio>
{
public:
    explicit StEthMdio(const StEthMdioConfig& config);

    /**
    * @brief Initialize the MDIO interface
    * @param config Configuration parameters for the MDIO interface
    */
    EoT::EthMdioStatus init();

    /**
    * @brief Read a register from a PHY device
    * @param phy_addr PHY address (0-31)
    * @param reg_addr Register address (0-31)
    * @param data Reference to store the read data
    * @return Status of the read operation
    */
    EoT::EthMdioStatus read(uint8_t phy_addr, uint8_t reg_addr, uint16_t& data);
    /**
    * @brief Write a register to a PHY device
    * @param phy_addr PHY address (0-31)
    * @param reg_addr Register address (0-31)
    * @param data Data to write
    * @return Status of the write operation
    */
    EoT::EthMdioStatus write(uint8_t phy_addr, uint8_t reg_addr, uint16_t data);

private:
    ETH_TypeDef* base_addr;
    uint32_t csr_clock_hz{0U};
    uint32_t timeout_ms{1000U};
    StEthMdioSettings settings;

    /**
    * @brief Check if the MDIO interface is busy
    * @return true if the MDIO interface is busy, false otherwise
    */
    bool is_busy() const;

    /**
    * @brief A wrapper for the entire busy check routine, which includes a timeout mechanism.
    */
    EthMdioStatus check_busy_routine() const;
};

}  // namespace EoT::StmH7